### ISSUE TITLE
Show how many unread messages

### ISSUE THREAD

**Issue by melroy89** [johndoh/roundcube-taskwatermark#3]
Just like Proton you could improve the text from "Select a message to read" to maybe something like: 

"Select a message to read. You have x unread message in your inbox.", in case you didn't read all your messages yet.

Again, just a proposal.

**Comment by johndoh** [comment]
I suppose when the screen is not big enough to show the folder list, the unread count is not immediately visible.

It seems like it might be quite a bit of code for such a limited use case.

Do you have another use case in mind?

**Comment by melroy89** [comment]
If it's very hard to fetch the unread count.. But I think it's just a nice touch. So people directly have useful information in the right panel.
